import eslint from "@eslint/js"
import reactHooks from "eslint-plugin-react-hooks"
import globals from "globals"
import tseslint from "typescript-eslint"

export default tseslint.config(
  {
    ignores: [
      "out/**",
      "release/**",
      "dist/**",
      "node_modules/**",
      // Agent worktrees are whole copies of the repo living under
      // .claude/, outside every tsconfig. Linting them buries the real
      // findings under hundreds of phantom parse errors.
      ".claude/**",
      // Generated by `pnpm generate:codex-protocol` — not ours to lint.
      "src/main/codex-protocol/generated/**",
      // Test fixtures are intentionally arbitrary content, not project code.
      "fixtures/**",
    ],
  },
  eslint.configs.recommended,
  {
    // Control characters in regexes are this domain: ANSI escape stripping,
    // record separators in archives.
    rules: { "no-control-regex": "off" },
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.eslint.json",
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // The codebase deliberately uses defensive `!` on indexed access
      // (noUncheckedIndexedAccess is off); auto-fixing ~200 sites would
      // reformat 35 files for no behavior change.
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      // Adapters, mocks, and bridges implement async interfaces; bodies
      // without awaits are the norm there (~120 sites).
      "@typescript-eslint/require-await": "off",
      // `String(x)` over untrusted JSON fields is deliberate coercion — the
      // "[object Object]" worst case just fails a later string match.
      "@typescript-eslint/no-base-to-string": "warn",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    files: ["src/renderer/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
  {
    // Tests stub adapters and parse ad-hoc JSON fixtures; the unsafe-* family
    // and no-explicit-any fight that style without catching real bugs there.
    files: ["tests/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },
  {
    // Shadowed out of the TS program by its sibling index.ts, so it cannot be
    // linted type-aware.
    files: ["src/preload/index.d.ts"],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    // Runtime Node scripts shipped as resources (not part of any tsconfig).
    files: ["resources/**/*.{js,mjs,cjs}"],
    languageOptions: { globals: globals.node },
  },
  {
    files: ["e2e/**/*.mjs"],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
  {
    files: ["src/renderer/public/**/*.js"],
    languageOptions: { globals: globals.browser },
  },
  {
    // Plain JS config files (including this one) get no type information.
    files: ["**/*.{js,mjs,cjs}"],
    extends: [tseslint.configs.disableTypeChecked],
  },
)
